# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  name: Default
  demands:
    -agent.name -equals myagent
variables:
  - group: "ASOC"

stages:
  - stage: OX_Security_Scan
    displayName: OX Security Scan
    jobs:
      - job: OX
        displayName: Run OX Security Scan
        steps:
          - script: |
              docker run \
              -e OX_HOST_URL=$(ASOC_HOST) \
              -e OX_API_KEY=$(ASOC_TOKEN) \
              -e OX_DISABLE_SSL_VALIDATION=true \
              --env-file <(env | grep 'SYSTEM_\|BUILD_') \
              oxsecurity/ox-block-mode:latest
            displayName: Execute OX Security Scan


