name: Example workflow with OX Security Scan
on:
  push:
    branches:
      - master
  pull_request:
    types: [main, opened, reopened, synchronize]
    branches:
      - master
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Run OX Security Scan to check for vulnerabilities
        with:
          ox_host_url: https://app.bosch.onprem3.dev.ox.security
          ox_api_key: ${{ secrets.OX_API_KEY }}
          ox_override_blocking: true
        uses: oxsecurity/ox-security-scan@main
